### ISSUE TITLE
Dropdown not clickable at random times

### ISSUE THREAD

**Issue by vighneshmufc** [CLIxIndia-Dev/CLIxDashboard#28]
**Align Useful Links Content Positioning Properly**
As a Test Engineer, I  want to see the drop down be clickable at all times so that it makes the website user friendly.

**To Reproduce**
1. Go to 'https://staging-clixdashboard.tiss.edu/home'
2. Scroll to Useful Links
3. See error

**Expected behavior**
Inconsistency need to be removed.. needs triage
**Screenshots**
![Screenshot (388)](https://user-images.githubusercontent.com/14256897/112932702-0271a680-913c-11eb-971e-ea5285cebfcd.png)

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [chrome]
 - Version [89.0]

**Comment by yogeshu** [comment]
![Screenshot from 2021-03-30 13-48-15](https://user-images.githubusercontent.com/32289745/112956952-994f5a80-915e-11eb-9f4a-5a31fdb02de4.png)
- Now links are accessible from empty space.

**Comment by vighneshmufc** [comment]
seems buggy at random times

**Comment by yogeshu** [comment]
what is the bug ? @vighneshmufc

**Comment by vighneshmufc** [comment]
Happens randomly when i am not able to click dashboard it goes out of view

**Comment by yogeshu** [comment]
The Menu is based on hover on link , as you left hover effect it will be disabled , there is no click event for large screen for useful links - It was suggestion that we need to have links over hover effect.

**Comment by VirajUtekar** [comment]
**Expectation:**
The alignment should be proper of link text, it was going out of screen

**Actual:**
The alignment is now proper of link text, sits within screen

**Status**
This issue is been resolved

**Screenshot:**
![Screenshot from 2021-12-24 21-49-33](https://user-images.githubusercontent.com/90617515/147364373-c4744378-e0ee-402a-9425-d2642c68d452.png)

**Desktop:**

-   OS:[Ubuntu 20.04.3]
-   Browser:[Chrome]
-   Version:[95]
