### ISSUE TITLE
Footer Links opening on same tab/window

### ISSUE THREAD

**Issue by vighneshmufc** [CLIxIndia-Dev/CLIxDashboard#41]
**FAQ Question on Hover Color Change**
As a Test Engineer, I want to see the footer links open on different page
**To Reproduce**
1. Go to 'https://staging-clixdashboard.tiss.edu/home'
2. Scroll on 'Footer and click on any link'
3. See error

**Expected behavior**
Links should open in new tab
**Screenshots**
![image](https://user-images.githubusercontent.com/14256897/119805089-8fe43380-befe-11eb-9d41-3e46c93af9ba.png)
**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [chrome]
 - Version [89.0]

**Comment by vighneshmufc** [comment]
@yogeshu  Not fixed

**Comment by yogeshu** [comment]
Please mentioned which links? If it is about and all I wasn't aware that need to be open on another page.

**Comment by vighneshmufc** [comment]
all of them

**Comment by VirajUtekar** [comment]
**Expected**:
when clicked on all footer links it should open page on new window tab

**Actual**:
when clicked on all footer links it opens page on new window tab

**Status**
This issue is been resolved

**Desktop**
   OS : [Ubuntu 20.0.4]
   Browser: [Chrome]
   Version: [95]
 
**Screenshot**
![Screenshot from 2021-12-24 14-33-50](https://user-images.githubusercontent.com/90617515/147338022-1e4eac9a-f479-488e-b2df-55daf7d0a0e1.png)

![Screenshot from 2021-12-24 14-35-53](https://user-images.githubusercontent.com/90617515/147338165-ad03af86-0c5d-4a08-9d1d-d86e47a61aec.png)
