### ISSUE TITLE
Name of School needs better formatting

### ISSUE THREAD

**Issue by vighneshmufc** [CLIxIndia-Dev/CLIxDashboard#46]
**Describe the bug**
As a Test Engineer i want to see the  whole school name properly for better for UI experience

**To Reproduce**
1. Go to 'https://staging-clixdashboard.tiss.edu/home'
2. Click on 'Select School'
3. Scroll down to 'Any School'

**Expected behavior**
The School name should come properly without any cuts etc.
**Screenshots**
![image](https://user-images.githubusercontent.com/14256897/120135579-34f85800-c1ee-11eb-835d-f838df92c538.png)

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [Chrome
 - Version [89]

**Comment by yogeshu** [comment]
This is not possible as input is not dynamic and it has to look good on the mobile screen. The school name includes a lot of things. Need to discuss this with the team then if this needs to be dynamic which is again not good

**Comment by vighneshmufc** [comment]
@SadaqatMulla Needs review

**Comment by VirajUtekar** [comment]
**Expected**
Under school drop-down list, there should be full name display.

**Actual**
Under school drop-down list, there is full name displayed

**Status**
This issue is been resolved

**Screenshot**
![Screenshot from 2021-12-24 14-48-19](https://user-images.githubusercontent.com/90617515/147343419-74fbbe56-5027-4913-b726-5910ca62f436.png)

**Desktop**
  OS:[Ubuntu 20.0.04]
  Browser:[Chrome]
  Version: [95]

  Browser: [Firefox]
  Version:[95.0.1]
